name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Install vale
        run: deno install --allow-env --allow-read --allow-write --allow-net --unstable -n vale https://deno.land/x/vale@0.1.4/mod.ts

      - name: Build the website
        run: vale build docs

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "YOUR_DENO_DEPLOY_PROJECT_NAME"
          entrypoint: "./server.ts"
